import random as rd

#dado = rd.randint(1, 6)
#print(dado)
#for _ in range(10):
#    dado = rd.randint(1, 6)
#    print(dado)

# lista de 20 numeros aleatorios entre 1 y 10
# l = []
# for _ in range(20):
#     numero = rd.randint(1, 10)
#     l.append(numero)
# print(l)

# l = [ rd.randint(1, 10) for _ in range(20) ]
# print(l)


# choice
# randrange
# sample
# shuffle
# randint

# carta = rd.randint(1, 52)
#import random as rd

#lestudiantes = ['AUQUILLA AUQUILLA LILIANA ELIZABETH', 'BAQUERIZO BRIONES IVANNA AZUCENA', 'BUESTAN CASTILLO JORDAN GREGORY', 'CAÑIZARES JALON JUAN DIEGO', 'CEREZO CERVANTES JUAN SEBASTIAN', 'CORNEJO ROJAS DANIEL ISAAC', 'FIGUEROA LEON ASAHEL DE JESUS', 'GOYA BAYAS RENATO ALEXANDER', 'GUEVARA SANCHEZ AARON ALEXANDER', 'GUILLEN CEDEÑO ANTHONY ELIER', 'GUINGLA VELEZ ALLAN DANIEL', 'IZA CHIPANTIZA BRYAN ISRAEL', 'LLERENA GELLIBERT AARON ALEJANDRO', 'LUNA BORJA STEPHANO EMILIO', 'MENDOZA LEON ADRIAN ELISEO', 'MOLINA MONTALVAN LINDA MARIUXI', 'MORALES CASTILLO KEVIN JAVIER', 'MORALES REYES CARLOS LUIS', 'NARVAEZ TENEMASA JORDY STEVEN', 'NIETO LEAL JOHN ANTHONY', 'PEREZ PUGLLA DERECK ANDRES', 'PIZARRO MORLA JEREMY ALEXANDER', 'QUIROGA RAMIREZ MARCELO FERNANDO', 'ROMERO BERMEO SANTIAGO PATRICIO', 'SANCHEZ QUINTO ROBERTO ANDRES', 'SUAREZ LEON CRISTOBAL JAVIER', 'TAMAYO CAMPOS MATEO ALFONSO', 'TORRES BRIONES MARCO NATHAN', 'VALLADARES FLORES VALERIA NOEMI', 'VALLEJO RODRIGUEZ KRISTOPHER ANGELO', 'VERA PINCAY ELKINS AYSIN', 'VILLACRES FARFAN JUAN PABLO', 'ZAMBRANO DELGADO IVAN EDUARDO', 'ZARATE LUCAS ERICK XAVIER', 'ZUÑIGA TOMALA ALEX ANTHONY', 'CHICA CARCHIPULLA PAUL LEANDRO']
#nombre = rd.choice(lestudiantes)
#print(nombre)

# 10 numeros aleatorios entre 1 - 1000 step = 2
# pero que solo sean pares
# for _ in range(3):
#     numero = rd.randrange(2, 11, 2)
#     print(numero)

#lestudiantes = ['AUQUILLA AUQUILLA LILIANA ELIZABETH', 'BAQUERIZO BRIONES IVANNA AZUCENA', 'BUESTAN CASTILLO JORDAN GREGORY', 'CAÑIZARES JALON JUAN DIEGO', 'CEREZO CERVANTES JUAN SEBASTIAN', 'CORNEJO ROJAS DANIEL ISAAC', 'FIGUEROA LEON ASAHEL DE JESUS', 'GOYA BAYAS RENATO ALEXANDER', 'GUEVARA SANCHEZ AARON ALEXANDER', 'GUILLEN CEDEÑO ANTHONY ELIER', 'GUINGLA VELEZ ALLAN DANIEL', 'IZA CHIPANTIZA BRYAN ISRAEL', 'LLERENA GELLIBERT AARON ALEJANDRO', 'LUNA BORJA STEPHANO EMILIO', 'MENDOZA LEON ADRIAN ELISEO', 'MOLINA MONTALVAN LINDA MARIUXI', 'MORALES CASTILLO KEVIN JAVIER', 'MORALES REYES CARLOS LUIS', 'NARVAEZ TENEMASA JORDY STEVEN', 'NIETO LEAL JOHN ANTHONY', 'PEREZ PUGLLA DERECK ANDRES', 'PIZARRO MORLA JEREMY ALEXANDER', 'QUIROGA RAMIREZ MARCELO FERNANDO', 'ROMERO BERMEO SANTIAGO PATRICIO', 'SANCHEZ QUINTO ROBERTO ANDRES', 'SUAREZ LEON CRISTOBAL JAVIER', 'TAMAYO CAMPOS MATEO ALFONSO', 'TORRES BRIONES MARCO NATHAN', 'VALLADARES FLORES VALERIA NOEMI', 'VALLEJO RODRIGUEZ KRISTOPHER ANGELO', 'VERA PINCAY ELKINS AYSIN', 'VILLACRES FARFAN JUAN PABLO', 'ZAMBRANO DELGADO IVAN EDUARDO', 'ZARATE LUCAS ERICK XAVIER', 'ZUÑIGA TOMALA ALEX ANTHONY', 'CHICA CARCHIPULLA PAUL LEANDRO']
#muestra = rd.sample(lestudiantes, 3)
#muestra = rd.choices(lestudiantes, k=3)
#print(muestra)

# rd.shuffle(lestudiantes)
# print(lestudiantes)

# x = rd.randint(1, 20)
# print(x)
# import funciones as fn
# l = ['frank', 'pedro', 'juan', 'jesus', 'issac']
# resultado = fn.CuentaNoBarajados(l)
# print(resultado)



#palabra = "fundamentos"
#lletras = list(palabra)
#rd.shuffle(lletras)
#print(lletras)
#palabra = "".join(lletras)
#print(palabra)
