
import random as rd
# total = rd.randint(10, 200)
# print(total)
# if total >= 100 :
#     total = total - (total * 0.1)
# print(total)


# semaforo = rd.choice(['rojo', 'amarillo', 'verde'])
# print(semaforo)
# if semaforo == 'verde':
#     print("avanzar")
# else: # else va solo, no lleva condicion
#     print("detenerse")



# lestudiantes = ['AUQUILLA AUQUILLA LILIANA ELIZABETH', 'BAQUERIZO BRIONES IVANNA AZUCENA', 'BUESTAN CASTILLO JORDAN GREGORY', 'CAÑIZARES JALON JUAN DIEGO', 'CEREZO CERVANTES JUAN SEBASTIAN', 'CORNEJO ROJAS DANIEL ISAAC', 'FIGUEROA LEON ASAHEL DE JESUS', 'GOYA BAYAS RENATO ALEXANDER', 'GUEVARA SANCHEZ AARON ALEXANDER', 'GUILLEN CEDEÑO ANTHONY ELIER', 'GUINGLA VELEZ ALLAN DANIEL', 'IZA CHIPANTIZA BRYAN ISRAEL', 'LLERENA GELLIBERT AARON ALEJANDRO', 'LUNA BORJA STEPHANO EMILIO', 'MENDOZA LEON ADRIAN ELISEO', 'MOLINA MONTALVAN LINDA MARIUXI', 'MORALES CASTILLO KEVIN JAVIER', 'MORALES REYES CARLOS LUIS', 'NARVAEZ TENEMASA JORDY STEVEN', 'NIETO LEAL JOHN ANTHONY', 'PEREZ PUGLLA DERECK ANDRES', 'PIZARRO MORLA JEREMY ALEXANDER', 'QUIROGA RAMIREZ MARCELO FERNANDO', 'ROMERO BERMEO SANTIAGO PATRICIO', 'SANCHEZ QUINTO ROBERTO ANDRES', 'SUAREZ LEON CRISTOBAL JAVIER', 'TAMAYO CAMPOS MATEO ALFONSO', 'TORRES BRIONES MARCO NATHAN', 'VALLADARES FLORES VALERIA NOEMI', 'VALLEJO RODRIGUEZ KRISTOPHER ANGELO', 'VERA PINCAY ELKINS AYSIN', 'VILLACRES FARFAN JUAN PABLO', 'ZAMBRANO DELGADO IVAN EDUARDO', 'ZARATE LUCAS ERICK XAVIER', 'ZUÑIGA TOMALA ALEX ANTHONY', 'CHICA CARCHIPULLA PAUL LEANDRO']
# # imprimir los estudiantes que su
# # primera letra inicia con vocal
# vocales = ['A', 'E', 'I', 'O', 'U']
# for nombre in lestudiantes:
#     primera_letra = nombre[-1]
#     if primera_letra in vocales:
#         print(nombre)




# lestudiantes = ['AUQUILLA AUQUILLA LILIANA ELIZABETH', 'BAQUERIZO BRIONES IVANNA AZUCENA', 'BUESTAN CASTILLO JORDAN GREGORY', 'CAÑIZARES JALON JUAN DIEGO', 'CEREZO CERVANTES JUAN SEBASTIAN', 'CORNEJO ROJAS DANIEL ISAAC', 'FIGUEROA LEON ASAHEL DE JESUS', 'GOYA BAYAS RENATO ALEXANDER', 'GUEVARA SANCHEZ AARON ALEXANDER', 'GUILLEN CEDEÑO ANTHONY ELIER', 'GUINGLA VELEZ ALLAN DANIEL', 'IZA CHIPANTIZA BRYAN ISRAEL', 'LLERENA GELLIBERT AARON ALEJANDRO', 'LUNA BORJA STEPHANO EMILIO', 'MENDOZA LEON ADRIAN ELISEO', 'MOLINA MONTALVAN LINDA MARIUXI', 'MORALES CASTILLO KEVIN JAVIER', 'MORALES REYES CARLOS LUIS', 'NARVAEZ TENEMASA JORDY STEVEN', 'NIETO LEAL JOHN ANTHONY', 'PEREZ PUGLLA DERECK ANDRES', 'PIZARRO MORLA JEREMY ALEXANDER', 'QUIROGA RAMIREZ MARCELO FERNANDO', 'ROMERO BERMEO SANTIAGO PATRICIO', 'SANCHEZ QUINTO ROBERTO ANDRES', 'SUAREZ LEON CRISTOBAL JAVIER', 'TAMAYO CAMPOS MATEO ALFONSO', 'TORRES BRIONES MARCO NATHAN', 'VALLADARES FLORES VALERIA NOEMI', 'VALLEJO RODRIGUEZ KRISTOPHER ANGELO', 'VERA PINCAY ELKINS AYSIN', 'VILLACRES FARFAN JUAN PABLO', 'ZAMBRANO DELGADO IVAN EDUARDO', 'ZARATE LUCAS ERICK XAVIER', 'ZUÑIGA TOMALA ALEX ANTHONY', 'CHICA CARCHIPULLA PAUL LEANDRO']

# crear una funcion MideApellido que recibe un parametro entero n
# y la funcion retorna una lista con los nombres cuyos
# apellidos materno su longitud coincida con n

# n = ?
#
# def MideApellido(n):
#     lestudiantes = ['AUQUILLA AUQUILLA LILIANA ELIZABETH', 'BAQUERIZO BRIONES IVANNA AZUCENA',
#                     'BUESTAN CASTILLO JORDAN GREGORY', 'CAÑIZARES JALON JUAN DIEGO', 'CEREZO CERVANTES JUAN SEBASTIAN',
#                     'CORNEJO ROJAS DANIEL ISAAC', 'FIGUEROA LEON ASAHEL DE JESUS', 'GOYA BAYAS RENATO ALEXANDER',
#                     'GUEVARA SANCHEZ AARON ALEXANDER', 'GUILLEN CEDEÑO ANTHONY ELIER', 'GUINGLA VELEZ ALLAN DANIEL',
#                     'IZA CHIPANTIZA BRYAN ISRAEL', 'LLERENA GELLIBERT AARON ALEJANDRO', 'LUNA BORJA STEPHANO EMILIO',
#                     'MENDOZA LEON ADRIAN ELISEO', 'MOLINA MONTALVAN LINDA MARIUXI', 'MORALES CASTILLO KEVIN JAVIER',
#                     'MORALES REYES CARLOS LUIS', 'NARVAEZ TENEMASA JORDY STEVEN', 'NIETO LEAL JOHN ANTHONY',
#                     'PEREZ PUGLLA DERECK ANDRES', 'PIZARRO MORLA JEREMY ALEXANDER', 'QUIROGA RAMIREZ MARCELO FERNANDO',
#                     'ROMERO BERMEO SANTIAGO PATRICIO', 'SANCHEZ QUINTO ROBERTO ANDRES', 'SUAREZ LEON CRISTOBAL JAVIER',
#                     'TAMAYO CAMPOS MATEO ALFONSO', 'TORRES BRIONES MARCO NATHAN', 'VALLADARES FLORES VALERIA NOEMI',
#                     'VALLEJO RODRIGUEZ KRISTOPHER ANGELO', 'VERA PINCAY ELKINS AYSIN', 'VILLACRES FARFAN JUAN PABLO',
#                     'ZAMBRANO DELGADO IVAN EDUARDO', 'ZARATE LUCAS ERICK XAVIER', 'ZUÑIGA TOMALA ALEX ANTHONY',
#                     'CHICA CARCHIPULLA PAUL LEANDRO']
#     return [  nombre   for nombre in lestudiantes  if len(nombre.split(" ")[1]) == n ]
   # lretorno = []
    # for nombre in lestudiantes:
    #     # ap1, ap2, nom1, nom2 = nombre.split(" ")
    #     lpalabras = nombre.split(" ")
    #     apellido = lpalabras[1]
    #     if len(apellido) == n:
    #         lretorno.append(nombre)
    # return lretorno

# x = MideApellido(5)
# print(x)





#lestudiantes = ['AUQUILLA AUQUILLA LILIANA ELIZABETH', 'BAQUERIZO BRIONES IVANNA AZUCENA',
#                    'BUESTAN CASTILLO JORDAN GREGORY', 'CAÑIZARES JALON JUAN DIEGO', 'CEREZO CERVANTES JUAN SEBASTIAN',
#                    'CORNEJO ROJAS DANIEL ISAAC', 'FIGUEROA LEON ASAHEL DE JESUS', 'GOYA BAYAS RENATO ALEXANDER',
#                    'GUEVARA SANCHEZ AARON ALEXANDER', 'GUILLEN CEDEÑO ANTHONY ELIER', 'GUINGLA VELEZ ALLAN DANIEL',
#                    'IZA CHIPANTIZA BRYAN ISRAEL', 'LLERENA GELLIBERT AARON ALEJANDRO', 'LUNA BORJA STEPHANO EMILIO',
#                    'MENDOZA LEON ADRIAN ELISEO', 'MOLINA MONTALVAN LINDA MARIUXI', 'MORALES CASTILLO KEVIN JAVIER',
#                    'MORALES REYES CARLOS LUIS', 'NARVAEZ TENEMASA JORDY STEVEN', 'NIETO LEAL JOHN ANTHONY',
#                    'PEREZ PUGLLA DERECK ANDRES', 'PIZARRO MORLA JEREMY ALEXANDER', 'QUIROGA RAMIREZ MARCELO FERNANDO',
#                    'ROMERO BERMEO SANTIAGO PATRICIO', 'SANCHEZ QUINTO ROBERTO ANDRES', 'SUAREZ LEON CRISTOBAL JAVIER',
#                    'TAMAYO CAMPOS MATEO ALFONSO', 'TORRES BRIONES MARCO NATHAN', 'VALLADARES FLORES VALERIA NOEMI',
 #                   'VALLEJO RODRIGUEZ KRISTOPHER ANGELO', 'VERA PINCAY ELKINS AYSIN', 'VILLACRES FARFAN JUAN PABLO',
#                    'ZAMBRANO DELGADO IVAN EDUARDO', 'ZARATE LUCAS ERICK XAVIER', 'ZUÑIGA TOMALA ALEX ANTHONY',
#                    'CHICA CARCHIPULLA PAUL LEANDRO']

#import random as rd
#lnombresAleatorios = [  lestudiantes[rd.randint(0, len(lestudiantes) )]   for _ in range(5)]
#print(lnombresAleatorios)




