name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: testfile
      id: testfile
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testfile
        setup-command: ''
        command: make -f Testfile
        timeout: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTFILE_RESULTS: "${{steps.testfile.outputs.result}}"
      with:
        runners: testfile
